name: filtr
favicon: null
layout_spectrum: 0.49576
typography_spectrum: 0.5169341173022985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#415965'
    - '#55bdda'
    - '#9ca8af'
    - '#8761aa'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
